module.exports = {
  'post /ckan_govdata_rostock': 'register',
  'get /ckan_govdata_rostock': 'list',
  'get /ckan_govdata_rostock/:id': 'listall',
  'get /ckan_govdata_rostock/:id/:item.:format': 'findResource',
  'get /ckan_govdata_rostock/:id/:item': 'findResource',
  'post /ckan_govdata_rostock/:id/:item': 'findResource',
  'get /ckan_govdata_rostock/:id/:item/FeatureServer/:layer/:method': 'featureserver',
  'get /ckan_govdata_rostock/:id/:item/FeatureServer/:layer': 'featureserver',
  'get /ckan_govdata_rostock/:id/:item/FeatureServer': 'featureserver',
  'post /ckan_govdata_rostock/:id/:item/FeatureServer/:layer/:method': 'featureserver',
  'post /ckan_govdata_rostock/:id/:item/FeatureServer/:layer': 'featureserver',
  'post /ckan_govdata_rostock/:id/:item/FeatureServer': 'featureserver',
  'get /ckan_govdata_rostock/:id/:item/thumbnail': 'thumbnail',
  'get /ckan_govdata_rostock/:id/:item/tiles/:z/:x/:y.:format': 'tiles',
  'delete /ckan_govdata_rostock/:id': 'del',
  'get /ckan_govdata_rostock/:id/:item/preview': 'preview',
  'get /ckan_govdata_rostock/:id/:item/drop': 'drop'
}
